### ISSUE TITLE
SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by mlherd** [AI-Guru/gym-metacar#1]
Hi,

When I use the continuous action space environment, I get this error message.  

raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected number

Here is the code I tried.

import gym
import gym_metacar
import numpy as np
import time

env = gym.make("metacar-level3-continuous-v0")
env.reset()

for step in range(10):
	action = env.action_space.sample()
	observation, reward, done, info = env.step(action)
	env.render()
env.close()

If I create the action manually and use the env.step() function, the car doesn't move.
ex: action = [1, 0]

Thanks,
Melih

**Comment by AI-Guru** [comment]
You were very early! That is great dedication. 

It should work now.

**Comment by AI-Guru** [comment]
I have reopened this issue. The agent does indeed move, but very slowly.

**Comment by mlherd** [comment]
Thanks for the update! It is slow only if you don't' use env.enable_webrenderer(). At least that is what I noticed.

**Comment by AI-Guru** [comment]
Now it is definitely solved.
